// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: entity/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryGetEntityRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetEntityRequest) Reset()         { *m = QueryGetEntityRequest{} }
func (m *QueryGetEntityRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetEntityRequest) ProtoMessage()    {}
func (*QueryGetEntityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9b58e82145e4ece, []int{0}
}
func (m *QueryGetEntityRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetEntityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetEntityRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetEntityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetEntityRequest.Merge(m, src)
}
func (m *QueryGetEntityRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetEntityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetEntityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetEntityRequest proto.InternalMessageInfo

func (m *QueryGetEntityRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetEntityResponse struct {
	Entity *Entity `protobuf:"bytes,1,opt,name=Entity,proto3" json:"Entity,omitempty"`
}

func (m *QueryGetEntityResponse) Reset()         { *m = QueryGetEntityResponse{} }
func (m *QueryGetEntityResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetEntityResponse) ProtoMessage()    {}
func (*QueryGetEntityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9b58e82145e4ece, []int{1}
}
func (m *QueryGetEntityResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetEntityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetEntityResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetEntityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetEntityResponse.Merge(m, src)
}
func (m *QueryGetEntityResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetEntityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetEntityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetEntityResponse proto.InternalMessageInfo

func (m *QueryGetEntityResponse) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type QueryAllEntityRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllEntityRequest) Reset()         { *m = QueryAllEntityRequest{} }
func (m *QueryAllEntityRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllEntityRequest) ProtoMessage()    {}
func (*QueryAllEntityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9b58e82145e4ece, []int{2}
}
func (m *QueryAllEntityRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllEntityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllEntityRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllEntityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllEntityRequest.Merge(m, src)
}
func (m *QueryAllEntityRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllEntityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllEntityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllEntityRequest proto.InternalMessageInfo

func (m *QueryAllEntityRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllEntityResponse struct {
	Entity     []*Entity           `protobuf:"bytes,1,rep,name=Entity,proto3" json:"Entity,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllEntityResponse) Reset()         { *m = QueryAllEntityResponse{} }
func (m *QueryAllEntityResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllEntityResponse) ProtoMessage()    {}
func (*QueryAllEntityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9b58e82145e4ece, []int{3}
}
func (m *QueryAllEntityResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllEntityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllEntityResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllEntityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllEntityResponse.Merge(m, src)
}
func (m *QueryAllEntityResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllEntityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllEntityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllEntityResponse proto.InternalMessageInfo

func (m *QueryAllEntityResponse) GetEntity() []*Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *QueryAllEntityResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetEntityRequest)(nil), "dreamrs.entity.entity.QueryGetEntityRequest")
	proto.RegisterType((*QueryGetEntityResponse)(nil), "dreamrs.entity.entity.QueryGetEntityResponse")
	proto.RegisterType((*QueryAllEntityRequest)(nil), "dreamrs.entity.entity.QueryAllEntityRequest")
	proto.RegisterType((*QueryAllEntityResponse)(nil), "dreamrs.entity.entity.QueryAllEntityResponse")
}

func init() { proto.RegisterFile("entity/query.proto", fileDescriptor_f9b58e82145e4ece) }

var fileDescriptor_f9b58e82145e4ece = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4e, 0x22, 0x31,
	0x18, 0xc7, 0xe9, 0xec, 0x2e, 0xc9, 0x76, 0x93, 0x3d, 0x74, 0xc3, 0xc6, 0x10, 0x19, 0xcd, 0x44,
	0x85, 0x10, 0x6d, 0x03, 0xc6, 0x07, 0x80, 0x44, 0x39, 0xaa, 0x1c, 0xbd, 0x98, 0x0e, 0xd3, 0x8c,
	0x4d, 0x86, 0xe9, 0x30, 0x2d, 0x46, 0x62, 0xbc, 0xf8, 0x02, 0x6a, 0xbc, 0xf8, 0x12, 0xbe, 0x87,
	0x47, 0x12, 0x2f, 0x1e, 0x0d, 0xf8, 0x20, 0x86, 0xb6, 0x44, 0x40, 0x44, 0x4e, 0x9d, 0x7c, 0xf3,
	0xff, 0x7f, 0xff, 0xdf, 0xd7, 0xaf, 0x10, 0xb1, 0x58, 0x71, 0xd5, 0x23, 0x9d, 0x2e, 0x4b, 0x7b,
	0x38, 0x49, 0x85, 0x12, 0x28, 0x17, 0xa4, 0x8c, 0xb6, 0x53, 0x89, 0xcd, 0x3f, 0x7b, 0xe4, 0x57,
	0x43, 0x21, 0xc2, 0x88, 0x11, 0x9a, 0x70, 0x42, 0xe3, 0x58, 0x28, 0xaa, 0xb8, 0x88, 0xa5, 0x31,
	0xe5, 0xcb, 0x2d, 0x21, 0xdb, 0x42, 0x12, 0x9f, 0x4a, 0x66, 0xba, 0x91, 0xf3, 0x8a, 0xcf, 0x14,
	0xad, 0x90, 0x84, 0x86, 0x3c, 0xd6, 0x62, 0xab, 0xfd, 0x67, 0x43, 0x6d, 0x7f, 0x5d, 0xf4, 0x8a,
	0x30, 0x77, 0x3c, 0xb2, 0x35, 0x98, 0xda, 0xd7, 0xf5, 0x26, 0xeb, 0x74, 0x99, 0x54, 0xe8, 0x2f,
	0x74, 0x78, 0xb0, 0x02, 0xd6, 0x41, 0xe9, 0x67, 0xd3, 0xe1, 0x81, 0x77, 0x08, 0xff, 0xcf, 0x0a,
	0x65, 0x22, 0x62, 0xc9, 0xd0, 0x1e, 0xcc, 0x9a, 0x8a, 0x56, 0xff, 0xa9, 0x16, 0xf0, 0xdc, 0x49,
	0xb0, 0xb5, 0x59, 0xb1, 0x77, 0x6a, 0x93, 0x6b, 0x51, 0x34, 0x9d, 0x7c, 0x00, 0xe1, 0x07, 0xbb,
	0xed, 0xb9, 0x85, 0xcd, 0xa0, 0x78, 0x34, 0x28, 0x36, 0xd7, 0x66, 0x07, 0xc5, 0x47, 0x34, 0x64,
	0xd6, 0xdb, 0x9c, 0x70, 0x7a, 0x0f, 0xc0, 0x22, 0x4f, 0x24, 0xcc, 0x41, 0xfe, 0xb1, 0x34, 0x32,
	0x6a, 0x4c, 0x91, 0x39, 0x9a, 0xac, 0xf8, 0x2d, 0x99, 0xc9, 0x9c, 0x44, 0xab, 0x3e, 0x3a, 0xf0,
	0x97, 0x46, 0x43, 0x77, 0x60, 0x8c, 0x82, 0xb6, 0xbf, 0x80, 0x98, 0xbb, 0x9f, 0xfc, 0xce, 0x92,
	0x6a, 0x93, 0xee, 0x95, 0xaf, 0x9f, 0xdf, 0xee, 0x9d, 0x0d, 0xe4, 0x11, 0x6b, 0x23, 0x53, 0xaf,
	0x61, 0x7c, 0x5c, 0xf2, 0xe0, 0x0a, 0xdd, 0x00, 0xf8, 0xdb, 0xd8, 0x6b, 0x51, 0xb4, 0x18, 0x6b,
	0x76, 0x79, 0x8b, 0xb1, 0x3e, 0x2d, 0xc2, 0xdb, 0xd4, 0x58, 0x6b, 0xa8, 0xb0, 0x10, 0xab, 0x5e,
	0x7f, 0x1a, 0xb8, 0xa0, 0x3f, 0x70, 0xc1, 0xeb, 0xc0, 0x05, 0xb7, 0x43, 0x37, 0xd3, 0x1f, 0xba,
	0x99, 0x97, 0xa1, 0x9b, 0x39, 0x29, 0x85, 0x5c, 0x9d, 0x75, 0x7d, 0xdc, 0x12, 0xed, 0xd9, 0x16,
	0x17, 0xe3, 0x0f, 0xd5, 0x4b, 0x98, 0xf4, 0xb3, 0xfa, 0xc1, 0xef, 0xbe, 0x07, 0x00, 0x00, 0xff,
	0xff, 0x88, 0x8e, 0xc0, 0x48, 0x7c, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a entity by id.
	Entity(ctx context.Context, in *QueryGetEntityRequest, opts ...grpc.CallOption) (*QueryGetEntityResponse, error)
	// Queries a list of entity items.
	EntityAll(ctx context.Context, in *QueryAllEntityRequest, opts ...grpc.CallOption) (*QueryAllEntityResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Entity(ctx context.Context, in *QueryGetEntityRequest, opts ...grpc.CallOption) (*QueryGetEntityResponse, error) {
	out := new(QueryGetEntityResponse)
	err := c.cc.Invoke(ctx, "/dreamrs.entity.entity.Query/Entity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EntityAll(ctx context.Context, in *QueryAllEntityRequest, opts ...grpc.CallOption) (*QueryAllEntityResponse, error) {
	out := new(QueryAllEntityResponse)
	err := c.cc.Invoke(ctx, "/dreamrs.entity.entity.Query/EntityAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a entity by id.
	Entity(context.Context, *QueryGetEntityRequest) (*QueryGetEntityResponse, error)
	// Queries a list of entity items.
	EntityAll(context.Context, *QueryAllEntityRequest) (*QueryAllEntityResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Entity(ctx context.Context, req *QueryGetEntityRequest) (*QueryGetEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Entity not implemented")
}
func (*UnimplementedQueryServer) EntityAll(ctx context.Context, req *QueryAllEntityRequest) (*QueryAllEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EntityAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Entity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Entity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dreamrs.entity.entity.Query/Entity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Entity(ctx, req.(*QueryGetEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EntityAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EntityAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dreamrs.entity.entity.Query/EntityAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EntityAll(ctx, req.(*QueryAllEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dreamrs.entity.entity.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Entity",
			Handler:    _Query_Entity_Handler,
		},
		{
			MethodName: "EntityAll",
			Handler:    _Query_EntityAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "entity/query.proto",
}

func (m *QueryGetEntityRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetEntityRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetEntityRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetEntityResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetEntityResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetEntityResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Entity != nil {
		{
			size, err := m.Entity.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllEntityRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllEntityRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllEntityRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllEntityResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllEntityResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllEntityResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Entity) > 0 {
		for iNdEx := len(m.Entity) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Entity[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetEntityRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetEntityResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Entity != nil {
		l = m.Entity.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllEntityRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllEntityResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Entity) > 0 {
		for _, e := range m.Entity {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetEntityRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetEntityRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetEntityRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetEntityResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetEntityResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetEntityResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entity", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Entity == nil {
				m.Entity = &Entity{}
			}
			if err := m.Entity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllEntityRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllEntityRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllEntityRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllEntityResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllEntityResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllEntityResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entity", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Entity = append(m.Entity, &Entity{})
			if err := m.Entity[len(m.Entity)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
